name: Demo Action with Email Step

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 23f2002722@ds.study.iitm.ac.in
        run: echo "Hello, world!"
